apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: rudzmic1/wkontenerach:0.1
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healtz
            port: 5000
            httpHeaders:
            - name: Custom-Header
              value: ok
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healtz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 3