apiVersion: v1
kind: Service
metadata:
  name: my-service-node-port
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: NodePort